### ISSUE TITLE
API key missing 

### ISSUE THREAD

**Issue by sachin-sankar** [CodeWithSwastik/prsaw#11]
When used the output is Free api key is Missing.

**Comment by CoblinFrog** [comment]
You need an API key to access the module now. Get one here: https://api.pgamerx.com/register.
Add this to your code:
```
api_key = "API Key" #replace this with the key you got.
rs = RandomStuff(api_key = api_key)
```

**Comment by sachin-sankar** [comment]
> You need an API key to access the module now. Get one here: https://api.pgamerx.com/register.
> Add this to your code:
> ```
> api_key = "API Key" #replace this with the key you got.
> rs = RandomStuff(api_key = api_key)
> ```
> 

Thank You.

**Comment by sachin-sankar** [comment]
@CoblinFrog I still get this error when the command is used

```
Bot instialised
Ignoring exception in command ai:
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "<string>", line 33, in ai
TypeError: __init__() got an unexpected keyword argument 'api_key'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/discord/ext/commands/core.py", line 864, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'api_key'
```

**Comment by CoblinFrog** [comment]
I had the same error before as well. I resolved it by updating the prsaw module. Run this in the shell:
```
pip install prsaw -U
```

**Comment by FalseDev** [comment]
@Creepy-Creeper3625 Please close the issue if you've resolved your issue.

Thank you @CoblinFrog for helping out here!

**Comment by sachin-sankar** [comment]
@FalseDev The issue is not resolved yet.
