### ISSUE TITLE
Im getting some unusual errors

### ISSUE THREAD

**Issue by IntelligentCourage22** [CodeWithSwastik/prsaw#14]
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from prsaw import RandomStuff
  File "C:\Users\ansh0\AppData\Local\Programs\Python\Python38-32\lib\site-packages\prsaw\__init__.py", line 1, in <module>
    from .PRSAW import *
  File "C:\Users\ansh0\AppData\Local\Programs\Python\Python38-32\lib\site-packages\prsaw\PRSAW.py", line 2, in <module>
    from apiclient import APIClient, APIRouter, Get, endpoint
ImportError: cannot import name 'APIClient' from 'apiclient' (C:\Users\ansh0\AppData\Local\Programs\Python\Python38-32\lib\site-packages\apiclient\__init__.py)

I dont think this is an issue with my code

**Comment by orion-406** [comment]
so was this actually solved?
