### ISSUE TITLE
keyerror

### ISSUE THREAD

**Issue by Bob142853** [CodeWithSwastik/prsaw#31]
```py
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    response = rs.get_ai_response("How are you?")
  File "D:\Anaconda3\lib\site-packages\apiclient\core.py", line 95, in __call__
    return self.sync_call(httpx_request)
  File "D:\Anaconda3\lib\site-packages\apiclient\core.py", line 100, in sync_cal
l
    response = post_processor(response)
  File "D:\Anaconda3\lib\site-packages\prsaw\PRSAW.py", line 115, in _post_get_i
mage
    return res[0]
KeyError: 0
```

im getting the following error. why is that happening?

**Comment by Prezxcwy** [comment]
same

**Comment by Bob142853** [comment]
I still dont understand why swas wont fix this

**Comment by Prezxcwy** [comment]
I think this repo is discontinued.
