### ISSUE TITLE
httpcore.ConnectTimeout error when using `async_mode`.

### ISSUE THREAD

**Issue by izxxr** [CodeWithSwastik/prsaw#4]
I'm getting the following error when I'm using the `async_mode`. 
```
 File "/home/nerdguyahmad/.local/lib/python3.6/site-packages/httpcore/_async/connection.py", line 93, in arequest
    self.socket = await self._open_socket(timeout)
  File "/home/nerdguyahmad/.local/lib/python3.6/site-packages/httpcore/_async/connection.py", line 124, in _open_socket
    local_address=self.local_address,
  File "/home/nerdguyahmad/.local/lib/python3.6/site-packages/httpcore/_backends/auto.py", line 45, in open_tcp_stream
    hostname, port, ssl_context, timeout, local_address=local_address
  File "/home/nerdguyahmad/.local/lib/python3.6/site-packages/httpcore/_backends/asyncio.py", line 271, in open_tcp_stream
    stream_reader=stream_reader, stream_writer=stream_writer
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/nerdguyahmad/.local/lib/python3.6/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nerdguyahmad/.local/lib/python3.6/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 255, in on_message
    response= await rs.get_ai_response(msg.content)
  File "/home/nerdguyahmad/.local/lib/python3.6/site-packages/apiclient/core.py", line 104, in async_call
    response = await self.session.send(httpx_request)
  File "/home/nerdguyahmad/.local/lib/python3.6/site-packages/httpx/_client.py", line 1411, in send
    history=[],
  File "/home/nerdguyahmad/.local/lib/python3.6/site-packages/httpx/_client.py", line 1448, in _send_handling_auth
    history=history,
  File "/home/nerdguyahmad/.local/lib/python3.6/site-packages/httpx/_client.py", line 1476, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/home/nerdguyahmad/.local/lib/python3.6/site-packages/httpx/_client.py", line 1507, in _send_single_request
    ext={"timeout": timeout.as_dict()},
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/nerdguyahmad/.local/lib/python3.6/site-packages/httpx/_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ConnectTimeout
Future exception was never retrieved
future: <Future finished exception=gaierror(-3, 'Temporary failure in name resolution')>
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
```

When I don't enable `async_mode` it only raises the `socket.gaierror: [Errno -3] Temporary failure in name resolution` error.

**Comment by izxxr** [comment]
VPN was causing issues, I turned it off and now it's working.
